name: Integration Tests

# This workflow runs integration tests manually or on specific triggers
# It's separate from the main test workflow to avoid running expensive tests on every push

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main ]
    paths: [ 'tests/integration/**' ]  # Only when integration tests change
  pull_request:
    branches: [ main ]
    paths: [ 'tests/integration/**' ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    # Only run if OPENAI_API_KEY is available
    if: ${{ secrets.OPENAI_API_KEY }}
    
    strategy:
      matrix:
        python-version: ["3.11"]  # Only test on one version for integration tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Run only integration tests
        pytest tests/integration/ -v --tb=short
        
        # Optional: Run with coverage for integration tests
        # pytest tests/integration/ -v --cov=. --cov-report=xml
    
    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-results
        path: |
          .coverage
          htmlcov/
        retention-days: 7
