name: Integration Tests

# This workflow runs integration tests manually or on specific triggers
# It's separate from the main test workflow to avoid running expensive tests on every push

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main, update-app-for-two-paragraph-poem ]
    paths: [ 'tests/integration/**' ]  # Only when integration tests change
  pull_request:
    branches: [ main ]
    paths: [ 'tests/integration/**' ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug environment variables
      run: |
        echo "Checking environment variables..."
        echo "OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
        echo "SUPABASE_URL length: ${#SUPABASE_URL}"
        echo "SUPABASE_KEY length: ${#SUPABASE_KEY}"
        echo "OPENAI_API_KEY starts with: ${OPENAI_API_KEY:0:10}..."
        echo "SUPABASE_URL starts with: ${SUPABASE_URL:0:20}..."
        echo "SUPABASE_KEY starts with: ${SUPABASE_KEY:0:10}..."

    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        # Run integration tests using the CI test runner
        python scripts/run_ci_tests.py

    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          .coverage
          htmlcov/
        retention-days: 7
