name: Integration Tests

# This workflow runs integration tests manually or on specific triggers
# It's separate from the main test workflow to avoid running expensive tests on every push

on:
  # Removed pull_request trigger - test.yml already runs all tests including integration tests
  # This workflow is now only for manual execution via workflow_dispatch
  workflow_dispatch:  # Manual trigger only

# Prevent multiple test runs from interfering with each other
# Use same concurrency group as test.yml to prevent simultaneous Supabase DB access
concurrency:
  group: test-suite-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug environment variables
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "=== DEBUGGING SECRETS ==="
        echo "Checking if secrets are available..."

        if [ -z "$OPENAI_API_KEY" ]; then
          echo "❌ OPENAI_API_KEY is NOT set or empty"
        else
          echo "✅ OPENAI_API_KEY is set (length: ${#OPENAI_API_KEY})"
          echo "   Starts with: ${OPENAI_API_KEY:0:10}..."
        fi

        if [ -z "$SUPABASE_URL" ]; then
          echo "❌ SUPABASE_URL is NOT set or empty"
        else
          echo "✅ SUPABASE_URL is set (length: ${#SUPABASE_URL})"
          echo "   Starts with: ${SUPABASE_URL:0:20}..."
        fi

        if [ -z "$SUPABASE_KEY" ]; then
          echo "❌ SUPABASE_KEY is NOT set or empty"
        else
          echo "✅ SUPABASE_KEY is set (length: ${#SUPABASE_KEY})"
          echo "   Starts with: ${SUPABASE_KEY:0:10}..."
        fi

        echo "=== END DEBUGGING ==="

    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        # Run integration tests using the CI test runner
        python scripts/run_ci_tests.py

    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          .coverage
          htmlcov/
        retention-days: 7
