name: Pre-commit Hooks

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit

    - name: Run pre-commit hooks
      env:
        OPENAI_API_KEY: test-key-for-mocking
      run: |
        # Run pre-commit hooks on all files
        pre-commit run --all-files --show-diff-on-failure

    - name: Run tests (as part of pre-commit)
      env:
        OPENAI_API_KEY: test-key-for-mocking
      run: |
        # Run tests using the CI test runner
        python scripts/run_ci_tests.py
